name: pcmad
description: A new Flutter project.
publish_to: 'none' # Prevent accidental publication
version: 1.0.0+1
environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter  
  charts_flutter: ^0.12.0
  cupertino_icons: ^1.0.2
  flutter_plot: ^0.1.0
  math_expressions: ^2.0.0
  shared_preferences: ^2.2.3
  url_launcher: ^6.0.9
  http: ^0.13.3
  flutter_local_notifications: ^8.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/profile_photo.jpg
    - assets/background_image.jpg
